# Generated by Django 5.2.5 on 2025-08-24 08:49

import receipts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="invite",
            name="token",
            field=models.CharField(
                default=receipts.models.generate_token, max_length=64, unique=True
            ),
        ),
    ]
