services:
  web:
    build:
      context: .                # host path = Application/
      dockerfile: Dockerfile
    command: bash /app/docker/entrypoint.sh
    env_file:
      - .env.docker             # put DB creds + secrets here
    environment:
      DJANGO_SETTINGS_MODULE: pay4.settings

      # RDS connection (must match what worked in psql)
      POSTGRES_HOST: pay4-db.c984myi4m1sf.us-west-2.rds.amazonaws.com
      POSTGRES_PORT: "5432"
      POSTGRES_DB: pay4
      POSTGRES_USER: pay4app
      POSTGRES_PASSWORD: RishRish2001!   # <- the one that worked with psql

      # AWS etc…
      AWS_REGION: us-west-2
      AWS_STORAGE_BUCKET_NAME: pay4-receipts-rshah-dev
      TEXTRACT_MODE: live
      INVITE_BASE_URL: http://localhost:8000/invite/
    ports:
      - "8000:8000"
    volumes:
      - .:/app                  # mount your code into the container
      - ~/.aws:/home/appuser/.aws:ro   # let boto3 use your AWS profile
    restart: always

networks:
  default:
    driver: bridge
