version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pay4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #ports:
    #  - "5432:5432"
    volumes:
      - pay4_pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -lc "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 pay4.wsgi:application"
    environment:
      # Django
      DJANGO_SETTINGS_MODULE: pay4.settings
      # DB (django will read these, or use dj-database-url if you prefer)
      POSTGRES_DB: pay4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      # AWS
      AWS_REGION: us-west-2
      AWS_STORAGE_BUCKET_NAME: pay4-receipts-rshah-dev
      TEXTRACT_MODE: live    # set to 'live' when you want live Textract
      INVITE_BASE_URL: http://localhost:8000/invite/
      AWS_PROFILE: pay4
      # If you want to use your local profile inside container, mount ~/.aws below instead of keys:
      # AWS_ACCESS_KEY_ID: your_key
      # AWS_SECRET_ACCESS_KEY: your_secret
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ~/.aws:/home/appuser/.aws:ro   # so boto3 can use your 'pay4' profile if you set AWS_PROFILE
    

volumes:
  pay4_pgdata:
